### ISSUE TITLE
LUA issues

### ISSUE THREAD

**Issue by jonomurphy** [Qblolz/sArena#1]
Hey there,

Downloaded, but lots of LUA issues appear upon logging in:

45x sArena-1.8\Modules\auratracker.lua:85: attempt to index upvalue 'auraList' (a nil value)
sArena-1.8\Modules\auratracker.lua:40: in function <sArena\Modules\auratracker.lua:38>

Also, I can't actually see sarena ingame when I select test?

**Comment by Qblolz** [comment]
> Hey there,
> 
> Downloaded, but lots of LUA issues appear upon logging in:
> 
> 45x sArena-1.8\Modules\auratracker.lua:85: attempt to index upvalue 'auraList' (a nil value) sArena-1.8\Modules\auratracker.lua:40: in function <sArena\Modules\auratracker.lua:38>
> 
> Also, I can't actually see sarena ingame when I select test?

Whats your client - default 3.3.5 ? Addon atm only for 1 PS(PrivateServer) sirus.su
If you want to use, u can try this version before update for sirus.su
https://github.com/Qblolz/sArena/tree/dc15d1677a4638395d774e7ba953671351e8dd33
I`ll create release version for default 3.3.5 or branch

**Comment by Qblolz** [comment]
updt:
Try this release (tested on Warmane - with correct racials table)
https://github.com/Qblolz/sArena/releases/tag/1.0.0-default

**Comment by jonomurphy** [comment]
It works!Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Qblolz ***@***.***> Date: 14/12/2021  11:13  (GMT+00:00) To: Qblolz/sArena ***@***.***> Cc: BUDWIESER ***@***.***>, Author ***@***.***> Subject: Re: [Qblolz/sArena] LUA issues (Issue #1) 
updt:
Try this release (tested on Warmane - with correct racials table)
https://github.com/Qblolz/sArena/releases/tag/1.0.0-default

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Qblolz/sArena/issues/1#issuecomment-993434951",
"url": "https://github.com/Qblolz/sArena/issues/1#issuecomment-993434951",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
